### ISSUE TITLE
Support for Microsoft Teams

### ISSUE THREAD

**Issue by andreaswittig** [marbot-io/roadmap#1]
Support not only Slack, but Microsoft Teams as well.

**Comment by michaelwittig** [comment]
We are looking for closed beta testers. Reach out to us via email for details hello@marbot.io
<img width="613" alt="Screenshot 2020-04-27 at 19 27 00" src="https://user-images.githubusercontent.com/950078/80452005-91bb7c00-8925-11ea-9355-ea53c8bd7838.png">

**Comment by andreaswittig** [comment]
We are launching the public beta today! [marbot for Microsoft Teams (Beta)
](https://marbot.io/blog/marbot-for-microsoft-teams-beta.html).
