### ISSUE TITLE
Differentiate alarms from notifications

### ISSUE THREAD

**Issue by andreaswittig** [marbot-io/roadmap#16]
Not all incoming alarms need action. Find a way to send notifications instead of alarms to `@marbot`. For examle, a `SUCCESS` message from CodePipeline, Successful Elastic Beanstalk Deployment, ...

**Comment by nicholashahn** [comment]
The lack of having this is what has prevented us from subscribing to some RDS and Beanstalk events. I'd love if i was just a message to our channel, instead of @'ing people. An RDS instance restart isn't a problem that requires immediate dev attention - RDS will recover itself quickly enough.

**Comment by michaelwittig** [comment]
From one of our customers
> I was hoping to see in Slack when my code was deployed to AWS EB staging and Production environments

**Comment by michaelwittig** [comment]
We just released support for informational "alerts" aka notifications. The only supported source is Elastic Beanstalk at this time. I'm working on RDS.

Notifications are sent only to a Slack channel and can not be acknowledged/closed.

Keep in mind that you will see only one Slack message per Minute for each EB application&environment. If EB sends more notifications we will aggregate them to avoid a flood of messages: https://marbot.io/help/aggregation.html

**Comment by michaelwittig** [comment]
Where else would it make sense to support notifications?

* [x] RDS
* [x] CodePipeline Approval
* [ ] AWS Backup
* [ ] ElastiCache
* Subscription confirmation
  * [ ] EB
  * [ ] Budgets
  * [ ] ASG
  * [ ] RDS
  * [ ] S3
  * [ ] SES

**Comment by michaelwittig** [comment]
We just finished the work on notifications. Let us know if we missed important sources of such "notifications".

**Comment by michaelwittig** [comment]
Check out the launch blog post: https://marbot.io/blog/launch-of-notifications.html
