### ISSUE TITLE
Code* Notifications

### ISSUE THREAD

**Issue by andreaswittig** [marbot-io/roadmap#6]
Support new events from AWS CodeCommit, AWS CodeBuild, AWS CodeDeploy, and AWS CodePipeline. See [announcement](https://aws.amazon.com/about-aws/whats-new/2019/11/introducing-notifications-for-aws-codecommit-aws-codebuild-aws-codedeploy-and-asw-codepipeline/) for details.

**Comment by michaelwittig** [comment]
This seems to be related to #28 The events look very similar, we have to ensure that we aggregate them on the same key.
